In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df=pd.read_csv("data/raw/Atlantic_Spain.csv")
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [5]:
df['date_new'] = pd.to_datetime(df['date'], dayfirst=True)

counts = df.groupby('date_new').size()
counts.value_counts()

50     554
100      1
Name: count, dtype: int64

In [6]:
counts[counts != 50]

date_new
2025-03-01    100
dtype: int64

In [7]:
df[df['date_new'] == '2025-03-01'].sort_values('position')

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,date_new
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14400,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,79,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14401,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
...,...,...,...,...,...,...,...,...,...,...,...
14447,01-03-2025,48,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14448,01-03-2025,49,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...,2025-03-01
14398,01-03-2025,49,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01
14449,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01

In [8]:
# repeating values, dropping duplicates
df.drop_duplicates(subset=['date_new', 'position'], inplace=True)

In [9]:
df[df['date_new'] == '2025-03-01'].sort_values('position')

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,date_new
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...,2025-03-01
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...,2025-03-01
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...,2025-03-01
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...,2025-03-01
14357,01-03-2025,8,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,187172,single,1,False,https://i.scdn.co/image/ab67616d0000b2737b5840...,2025-03-01
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...,2025-03-01
14359,01-03-2025,10,Casanova,Soolking & Lola Indigo & Rvfv,83,243806,single,1,False,https://i.scdn.co/image/ab67616d0000b2732adf05...,2025-03-01
14360,01-03-2025,11,Gata Only,FloyyMenor & Cris Mj,90,222000,single,1,True,https://i.scdn.co/image/ab67616d0000b2731d0777...,2025-03-01
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...,2025-03-01
14362,01-03-2025,13,La_Original.mp3,Emilia,85,140625,album,13,False,https://i.scdn.co/image/ab67616d0000b273bfb945...,2025-03-01
14363,01-03-2025,14,LA ÚLTIMA,Quevedo,84,170322,single,1,False,https://i.scdn.co/image/ab67616d0000b27366a722...,2025-03-01
14364,01-03-2025,15,PERRO NEGRO,Bad Bunny,95,162767,album,22,True,https://i.scdn.co/image/ab67616d0000b2737b1fc5...,2025-03-01
14365,01-03-2025,16,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,232645,single,1,False,https://i.scdn.co/image/ab67616d0000b273531164...,2025-03-01
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...,2025-03-01
14367,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,60,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...,2025-03-01
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...,2025-03-01
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...,2025-03-01
14370,01-03-2025,21,Columbia,Quevedo,92,186000,single,1,False,https://i.scdn.co/image/ab67616d0000b273a00a81...,2025-03-01
14371,01-03-2025,22,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,235146,single,1,True,https://i.scdn.co/image/ab67616d0000b2734e3fa2...,2025-03-01
14372,01-03-2025,23,MODELITO,Mora,83,190496,album,14,True,https://i.scdn.co/image/ab67616d0000b273076ef0...,2025-03-01
14373,01-03-2025,24,LA CAPI,Myke Towers,80,202360,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
14374,01-03-2025,25,REINA,Mora,84,211879,album,15,True,https://i.scdn.co/image/ab67616d0000b2734cc96e...,2025-03-01
14375,01-03-2025,26,DILUVIO,Rauw Alejandro,90,197052,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...,2025-03-01
14376,01-03-2025,27,COSAS QUE NO TE DIJE,Saiko,84,224725,single,1,False,https://i.scdn.co/image/ab67616d0000b273fb045f...,2025-03-01
14377,01-03-2025,28,QLONA,KAROL G,93,172797,album,9,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,2025-03-01
14378,01-03-2025,29,EMPELOTICA,Lenny Tavárez & Feid,77,190322,single,1,True,https://i.scdn.co/image/ab67616d0000b2732733f7...,2025-03-01
14379,01-03-2025,30,Hey Lil Mama,Eladio Carrion,86,216338,album,17,False,https://i.scdn.co/image/ab67616d0000b273ec105e...,2025-03-01
14380,01-03-2025,31,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,173991,single,1,True,https://i.scdn.co/image/ab67616d0000b2735b8ec2...,2025-03-01
14381,01-03-2025,32,Madrid City,Ana Mena,79,172727,single,1,False,https://i.scdn.co/image/ab67616d0000b2739c3dc8...,2025-03-01
14382,01-03-2025,33,BABY HELLO,Rauw Alejandro,78,222461,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...,2025-03-01
14383,01-03-2025,34,OA,Anuel AA & Quevedo & Maluma,86,235200,single,1,True,https://i.scdn.co/image/ab67616d0000b27331e30d...,2025-03-01
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...,2025-03-01
14385,01-03-2025,36,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,248004,single,1,False,https://i.scdn.co/image/ab67616d0000b273dd62eb...,2025-03-01
14386,01-03-2025,37,La Bachata,Manuel Turizo,87,162637,album,15,False,https://i.scdn.co/image/ab67616d0000b2734dd995...,2025-03-01
14387,01-03-2025,38,LALA,Myke Towers,92,197920,album,23,True,https://i.scdn.co/image/ab67616d0000b2730656d5...,2025-03-01
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...,2025-03-01
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...,2025-03-01
14390,01-03-2025,41,Quien Es Dei V?,Dei V,81,162244,single,1,True,https://i.scdn.co/image/ab67616d0000b27348093f...,2025-03-01
14391,01-03-2025,42,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,172095,single,1,False,https://i.scdn.co/image/ab67616d0000b2733d2a29...,2025-03-01
14392,01-03-2025,43,lady madrizZz,céro,75,131020,single,1,False,https://i.scdn.co/image/ab67616d0000b2736eb7f1...,2025-03-01
14393,01-03-2025,44,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,215600,single,1,False,https://i.scdn.co/image/ab67616d0000b2732d6016...,2025-03-01
14394,01-03-2025,45,Holanda,Jhayco,86,231693,single,1,True,https://i.scdn.co/image/ab67616d0000b273cd2ceb...,2025-03-01
14395,01-03-2025,46,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,191320,single,1,True,https://i.scdn.co/image/ab67616d0000b27306eccb...,2025-03-01
14396,01-03-2025,47,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...,2025-03-01
14397,01-03-2025,48,El Mambo,Kiko Rivera,76,129845,single,1,False,https://i.scdn.co/image/ab67616d0000b2739550e7...,2025-03-01
14398,01-03-2025,49,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01

In [10]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df.drop(columns=['date_new'], inplace=True)

In [11]:
df.groupby('date').size().value_counts()

50    555
Name: count, dtype: int64

## Normalizing Song and artist naming

In [12]:
df['song'] = df['song'].str.strip().str.lower()
df['artist'] = df['artist'].str.strip().str.lower()

In [13]:
#creating a unique song id to identify individual songs

df['song_id'] = df['song'] + '_' + df['artist']

In [14]:

first_appearance = df.groupby('song_id')['date'].min().reset_index()
first_appearance.rename(columns={'date': 'entry_date'}, inplace=True)

In [15]:
df = df.merge(first_appearance, on='song_id', how='left')

In [16]:
df[['song', 'artist', 'date', 'entry_date']].head()

          song                      artist       date entry_date
0    supernova                       saiko 2024-05-18 2024-05-18
1     el tonto                 lola indigo 2024-05-18 2024-05-18
2    acróstico                     shakira 2024-05-18 2024-05-18
3         beso    rosalía & rauw alejandro 2024-05-18 2024-05-18
4  el merengue  marshmello & manuel turizo 2024-05-18 2024-05-18

In [17]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,song_id,entry_date
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...,supernova_saiko,2024-05-18
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...,el tonto_lola indigo,2024-05-18
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...,acróstico_shakira,2024-05-18
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...,beso_rosalía & rauw alejandro,2024-05-18
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...,el merengue_marshmello & manuel turizo,2024-05-18

In [18]:
song_group = df.groupby('song_id')

In [19]:
lifecycle_df = song_group.agg(
    entry_date=('date', 'min'),
    exit_date=('date', 'max')
).reset_index()

In [20]:
lifecycle_df['total_days'] = (
    lifecycle_df['exit_date'] - lifecycle_df['entry_date']
).dt.days + 1

#(+1 because same day = 1 day, not 0)

In [21]:
peak_pos = song_group['position'].min().reset_index()
peak_pos.rename(columns={'position': 'peak_position'}, inplace=True)

lifecycle_df = lifecycle_df.merge(peak_pos, on='song_id')

In [22]:
# time to peak

peak_dates = df.loc[df.groupby('song_id')['position'].idxmin()][['song_id', 'date']]
peak_dates.rename(columns={'date': 'peak_date'}, inplace=True)

lifecycle_df = lifecycle_df.merge(peak_dates, on='song_id')

lifecycle_df['time_to_peak'] = (
    lifecycle_df['peak_date'] - lifecycle_df['entry_date']
).dt.days

In [23]:
lifecycle_df.head()

,song_id,entry_date,exit_date,total_days,peak_position,peak_date,time_to_peak
0,0 confianza_rvfv,2025-06-02,2025-06-23,22,23,2025-06-07,5
1,"1 de enero, puntacana_rels b",2025-04-28,2025-04-28,1,45,2025-04-28,0
2,1000cosas_lola indigo & manuel turizo,2025-03-10,2025-11-13,249,3,2025-03-10,0
3,100xciento_foreign teck & eladio carrion & de ...,2025-04-30,2025-05-15,16,13,2025-05-11,11
4,14 febreros_quevedo,2025-11-24,2025-11-27,4,9,2025-11-24,0

In [24]:
df[df['song'].str.startswith(('0', '1'))][['song', 'artist']].head()

            song                       artist
14802  1000cosas  lola indigo & manuel turizo
14853  1000cosas  lola indigo & manuel turizo
14903  1000cosas  lola indigo & manuel turizo
14952  1000cosas  lola indigo & manuel turizo
15002  1000cosas  lola indigo & manuel turizo

In [25]:
lifecycle_df['song_id'].iloc[0]

'0 confianza_rvfv'

In [26]:
df[df['song_id'].str.startswith(('0','14'))]['song_id']

18939       0 confianza_rvfv
19080       0 confianza_rvfv
19124       0 confianza_rvfv
19172       0 confianza_rvfv
19222       0 confianza_rvfv
19278       0 confianza_rvfv
19327       0 confianza_rvfv
19377       0 confianza_rvfv
19425       0 confianza_rvfv
19475       0 confianza_rvfv
19525       0 confianza_rvfv
19575       0 confianza_rvfv
19627       0 confianza_rvfv
19677       0 confianza_rvfv
19728       0 confianza_rvfv
19778       0 confianza_rvfv
19829       0 confianza_rvfv
19883       0 confianza_rvfv
19941       0 confianza_rvfv
19991       0 confianza_rvfv
27558    14 febreros_quevedo
27612    14 febreros_quevedo
27665    14 febreros_quevedo
27715    14 febreros_quevedo
Name: song_id, dtype: object

those are just song names starting with numbers, like 0 confianza, 69, 14 febreros

In [27]:
df.to_csv("data/processed/cleaned_data.csv", index=False)
lifecycle_df.to_csv("data/processed/lifecycle_data.csv", index=False)

Lifecycle Stage Classification
Classify songs into stages:

• New Entry (≤7 days)
• Growth Phase (rank improving)
• Peak Phase (Top 10 stability)
• Mature Phase (stable mid-rank)
• Decline Phase (rank deterioration)

In [28]:
df['days_since_entry'] = (df['date'] - df['entry_date']).dt.days

In [29]:
df = df.sort_values(['song_id', 'date'])

In [30]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,song_id,entry_date,days_since_entry
18939,2025-06-02,40,0 confianza,rvfv,35,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,0
19080,2025-06-05,31,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,3
19124,2025-06-06,25,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,4
19172,2025-06-07,23,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,5
19222,2025-06-08,23,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,6

In [31]:
df['prev_position'] = df.groupby('song_id')['position'].shift(1)
df['rank_change'] = df['prev_position'] - df['position']

In [32]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,song_id,entry_date,days_since_entry,prev_position,rank_change
18939,2025-06-02,40,0 confianza,rvfv,35,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,0,NaN,NaN
19080,2025-06-05,31,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,3,40.0,9.0
19124,2025-06-06,25,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,4,31.0,6.0
19172,2025-06-07,23,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,5,25.0,2.0
19222,2025-06-08,23,0 confianza,rvfv,57,217500,album,20,False,https://i.scdn.co/image/ab67616d0000b273c172e8...,0 confianza_rvfv,2025-06-02,6,23.0,0.0

In [33]:
df['stage'] = 'Other'  # default

df.loc[df['days_since_entry'] <= 7, 'stage'] = 'New Entry'

In [34]:
# if song in top 10

df.loc[df['position'] <= 10, 'stage'] = 'Peak'

In [35]:
# if song is growing

df.loc[
    (df['rank_change'] > 0) & (df['stage'] == 'Other'),
    'stage'
] = 'Growth'

In [36]:
# if song is declining
df.loc[
    (df['rank_change'] < 0) & (df['stage'] == 'Other'),
    'stage'
] = 'Decline'

In [37]:
# song reached maturity

df.loc[df['stage'] == 'Other', 'stage'] = 'Mature'

In [38]:
df['stage'].value_counts()

stage
Decline      7746
Growth       5996
Mature       5834
Peak         5550
New Entry    2624
Name: count, dtype: int64

In [39]:
df[df['song_id'] == df['song_id'].iloc[0]][
    ['date', 'position', 'rank_change', 'stage']
]

            date  position  rank_change      stage
18939 2025-06-02        40          NaN  New Entry
19080 2025-06-05        31          9.0  New Entry
19124 2025-06-06        25          6.0  New Entry
19172 2025-06-07        23          2.0  New Entry
19222 2025-06-08        23          0.0  New Entry
19278 2025-06-09        29         -6.0  New Entry
19327 2025-06-10        28          1.0     Growth
19377 2025-06-11        28          0.0     Mature
19425 2025-06-12        26          2.0     Growth
19475 2025-06-13        26          0.0     Mature
19525 2025-06-14        26          0.0     Mature
19575 2025-06-15        26          0.0     Mature
19627 2025-06-16        28         -2.0    Decline
19677 2025-06-17        28          0.0     Mature
19728 2025-06-18        29         -1.0    Decline
19778 2025-06-19        29          0.0     Mature
19829 2025-06-20        30         -1.0    Decline
19883 2025-06-21        34         -4.0    Decline
19941 2025-06-22        42         -8.0    Decline
19991 2025-06-23        42          0.0     Mature

In [40]:
lifecycle_df.head()

,song_id,entry_date,exit_date,total_days,peak_position,peak_date,time_to_peak
0,0 confianza_rvfv,2025-06-02,2025-06-23,22,23,2025-06-07,5
1,"1 de enero, puntacana_rels b",2025-04-28,2025-04-28,1,45,2025-04-28,0
2,1000cosas_lola indigo & manuel turizo,2025-03-10,2025-11-13,249,3,2025-03-10,0
3,100xciento_foreign teck & eladio carrion & de ...,2025-04-30,2025-05-15,16,13,2025-05-11,11
4,14 febreros_quevedo,2025-11-24,2025-11-27,4,9,2025-11-24,0

In [41]:
df.to_csv("data/processed/data_with_stages.csv", index=False)

Playlist Rotation & Churn Analysis
• Daily entry and exit counts
• Average churn rate
• Stability vs volatility measurement
• Rotation comparison across months

In [42]:
daily_songs = df.groupby('date')['song_id'].apply(set).reset_index()

In [43]:
daily_songs

          date                                            song_id
0   2024-05-18  {antes_rvfv & edu garcía, classy 101_feid & yo...
1   2024-05-19  {antes_rvfv & edu garcía, classy 101_feid & yo...
2   2024-05-20  {antes_rvfv & edu garcía, classy 101_feid & yo...
3   2024-05-21  {antes_rvfv & edu garcía, classy 101_feid & yo...
4   2024-05-22  {antes_rvfv & edu garcía, classy 101_feid & yo...
..         ...                                                ...
550 2025-11-23  {martini_dei v, me has invitado a bailar_dani ...
551 2025-11-24  {mr. moondial_quevedo, me has invitado a baila...
552 2025-11-25  {mr. moondial_quevedo, me has invitado a baila...
553 2025-11-26  {mr. moondial_quevedo, me has invitado a baila...
554 2025-11-27  {mr. moondial_quevedo, me has invitado a baila...

[555 rows x 2 columns]

In [44]:
daily_songs = daily_songs.sort_values('date')
daily_songs

          date                                            song_id
0   2024-05-18  {antes_rvfv & edu garcía, classy 101_feid & yo...
1   2024-05-19  {antes_rvfv & edu garcía, classy 101_feid & yo...
2   2024-05-20  {antes_rvfv & edu garcía, classy 101_feid & yo...
3   2024-05-21  {antes_rvfv & edu garcía, classy 101_feid & yo...
4   2024-05-22  {antes_rvfv & edu garcía, classy 101_feid & yo...
..         ...                                                ...
550 2025-11-23  {martini_dei v, me has invitado a bailar_dani ...
551 2025-11-24  {mr. moondial_quevedo, me has invitado a baila...
552 2025-11-25  {mr. moondial_quevedo, me has invitado a baila...
553 2025-11-26  {mr. moondial_quevedo, me has invitado a baila...
554 2025-11-27  {mr. moondial_quevedo, me has invitado a baila...

[555 rows x 2 columns]

In [45]:

#entries = today - yesterday
#exits   = yesterday - today

entries = []
exits = []

for i in range(len(daily_songs)):
    if i == 0:
        entries.append(0)
        exits.append(0)
    else:
        prev_set = daily_songs.loc[i-1, 'song_id']
        curr_set = daily_songs.loc[i, 'song_id']
        
        new_entries = len(curr_set - prev_set)
        new_exits = len(prev_set - curr_set)
        
        entries.append(new_entries)
        exits.append(new_exits)

daily_songs['entries'] = entries
daily_songs['exits'] = exits

In [46]:
daily_songs

,date,song_id,entries,exits
0,2024-05-18,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0
1,2024-05-19,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0
2,2024-05-20,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0
3,2024-05-21,"{antes_rvfv & edu garcía, classy 101_feid & yo...",4,4
4,2024-05-22,"{antes_rvfv & edu garcía, classy 101_feid & yo...",1,1
...,...,...,...,...
550,2025-11-23,"{martini_dei v, me has invitado a bailar_dani ...",1,1
551,2025-11-24,"{mr. moondial_quevedo, me has invitado a baila...",20,20
552,2025-11-25,"{mr. moondial_quevedo, me has invitado a baila...",2,2
553,2025-11-26,"{mr. moondial_quevedo, me has invitado a baila...",2,2
554,2025-11-27,"{mr. moondial_quevedo, me has invitado a baila...",3,3

In [47]:
daily_songs['churn_rate'] = daily_songs['entries'] / 50

# playlist size = 50

In [48]:
daily_songs

,date,song_id,entries,exits,churn_rate
0,2024-05-18,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00
1,2024-05-19,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00
2,2024-05-20,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00
3,2024-05-21,"{antes_rvfv & edu garcía, classy 101_feid & yo...",4,4,0.08
4,2024-05-22,"{antes_rvfv & edu garcía, classy 101_feid & yo...",1,1,0.02
...,...,...,...,...,...
550,2025-11-23,"{martini_dei v, me has invitado a bailar_dani ...",1,1,0.02
551,2025-11-24,"{mr. moondial_quevedo, me has invitado a baila...",20,20,0.40
552,2025-11-25,"{mr. moondial_quevedo, me has invitado a baila...",2,2,0.04
553,2025-11-26,"{mr. moondial_quevedo, me has invitado a baila...",2,2,0.04
554,2025-11-27,"{mr. moondial_quevedo, me has invitado a baila...",3,3,0.06

In [49]:

avg_churn = daily_songs['churn_rate'].mean()
avg_churn

np.float64(0.03434234234234235)

0.03==3.4% of 50 ≈ 1.7 songs/day
1-2 songs change per day, very stable playlist

In [50]:
daily_songs['month'] = daily_songs['date'].dt.to_period('M')

monthly_churn = daily_songs.groupby('month')['churn_rate'].mean().reset_index()
daily_songs

,date,song_id,entries,exits,churn_rate,month
0,2024-05-18,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00,2024-05
1,2024-05-19,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00,2024-05
2,2024-05-20,"{antes_rvfv & edu garcía, classy 101_feid & yo...",0,0,0.00,2024-05
3,2024-05-21,"{antes_rvfv & edu garcía, classy 101_feid & yo...",4,4,0.08,2024-05
4,2024-05-22,"{antes_rvfv & edu garcía, classy 101_feid & yo...",1,1,0.02,2024-05
...,...,...,...,...,...,...
550,2025-11-23,"{martini_dei v, me has invitado a bailar_dani ...",1,1,0.02,2025-11
551,2025-11-24,"{mr. moondial_quevedo, me has invitado a baila...",20,20,0.40,2025-11
552,2025-11-25,"{mr. moondial_quevedo, me has invitado a baila...",2,2,0.04,2025-11
553,2025-11-26,"{mr. moondial_quevedo, me has invitado a baila...",2,2,0.04,2025-11
554,2025-11-27,"{mr. moondial_quevedo, me has invitado a baila...",3,3,0.06,2025-11

In [51]:
monthly_churn

      month  churn_rate
0   2024-05    0.028571
1   2024-06    0.024000
2   2024-07    0.020000
3   2024-08    0.021290
4   2024-09    0.026667
5   2024-10    0.038065
6   2024-11    0.030000
7   2024-12    0.043226
8   2025-01    0.040645
9   2025-02    0.019286
10  2025-03    0.035862
11  2025-04    0.053333
12  2025-05    0.034194
13  2025-06    0.038000
14  2025-07    0.031333
15  2025-08    0.038000
16  2025-09    0.030000
17  2025-10    0.032258
18  2025-11    0.067407

In [52]:
import plotly.express as px

fig = px.line(daily_songs, x='date', y='churn_rate', title='Daily Churn Rate')
fig.show()

In [54]:
monthly_churn['month'] = monthly_churn['month'].astype(str)

In [55]:
px.bar(monthly_churn, x='month', y='churn_rate', title='Monthly Churn Comparison')

In [56]:
daily_songs.to_csv("data/processed/daily_churn.csv", index=False)