In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [20]:
df=pd.read_csv("datasets/Atlantic_Spain.csv")
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [22]:
df['date_new'] = pd.to_datetime(df['date'], dayfirst=True)

counts = df.groupby('date_new').size()
counts.value_counts()

50     554
100      1
Name: count, dtype: int64

In [23]:
counts[counts != 50]

date_new
2025-03-01    100
dtype: int64

In [24]:
df[df['date_new'] == '2025-03-01'].sort_values('position')

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,date_new
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14400,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,79,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14401,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
...,...,...,...,...,...,...,...,...,...,...,...
14447,01-03-2025,48,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14448,01-03-2025,49,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...,2025-03-01
14398,01-03-2025,49,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01
14449,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01

In [25]:
# repeating values, dropping duplicates
df.drop_duplicates(subset=['date_new', 'position'], inplace=True)

In [26]:
df[df['date_new'] == '2025-03-01'].sort_values('position')

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,date_new
14350,01-03-2025,1,FARDOS,JC Reyes & De La Ghetto,78,183335,single,1,False,https://i.scdn.co/image/ab67616d0000b27344d0e1...,2025-03-01
14351,01-03-2025,2,Manos Rotas,DELLAFUENTE & Morad,85,168594,single,1,False,https://i.scdn.co/image/ab67616d0000b2731a176d...,2025-03-01
14352,01-03-2025,3,LA FALDA,Myke Towers,94,174229,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
14353,01-03-2025,4,X'CLUSIVO,Gonzy,81,175586,single,1,True,https://i.scdn.co/image/ab67616d0000b2730d794d...,2025-03-01
14354,01-03-2025,5,LUNA,Feid,97,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...,2025-03-01
14355,01-03-2025,6,M.A.I,Milo j,89,184027,album,10,False,https://i.scdn.co/image/ab67616d0000b27398ee8f...,2025-03-01
14356,01-03-2025,7,Una Foto Remix (feat. Emilia),Mesita & Nicki Nicole & Tiago PZK,92,243898,single,1,False,https://i.scdn.co/image/ab67616d0000b273d7e325...,2025-03-01
14357,01-03-2025,8,"Young Miko: Bzrp Music Sessions, Vol. 58",Bizarrap & Young Miko,94,187172,single,1,False,https://i.scdn.co/image/ab67616d0000b2737b5840...,2025-03-01
14358,01-03-2025,9,Mamichula - con Nicki Nicole,Trueno,88,219201,album,10,False,https://i.scdn.co/image/ab67616d0000b273f4483d...,2025-03-01
14359,01-03-2025,10,Casanova,Soolking & Lola Indigo & Rvfv,83,243806,single,1,False,https://i.scdn.co/image/ab67616d0000b2732adf05...,2025-03-01
14360,01-03-2025,11,Gata Only,FloyyMenor & Cris Mj,90,222000,single,1,True,https://i.scdn.co/image/ab67616d0000b2731d0777...,2025-03-01
14361,01-03-2025,12,No Te Quieren Conmigo,Gaby Music & Lunay & Luar La L,89,252040,single,1,False,https://i.scdn.co/image/ab67616d0000b2732a3429...,2025-03-01
14362,01-03-2025,13,La_Original.mp3,Emilia,85,140625,album,13,False,https://i.scdn.co/image/ab67616d0000b273bfb945...,2025-03-01
14363,01-03-2025,14,LA ÚLTIMA,Quevedo,84,170322,single,1,False,https://i.scdn.co/image/ab67616d0000b27366a722...,2025-03-01
14364,01-03-2025,15,PERRO NEGRO,Bad Bunny,95,162767,album,22,True,https://i.scdn.co/image/ab67616d0000b2737b1fc5...,2025-03-01
14365,01-03-2025,16,El Patio,Pepe y Vizio & Delaossa & KIDDO,73,232645,single,1,False,https://i.scdn.co/image/ab67616d0000b273531164...,2025-03-01
14366,01-03-2025,17,UNA BACHATA,Lola Indigo,77,157846,album,7,False,https://i.scdn.co/image/ab67616d0000b27346dd0b...,2025-03-01
14367,01-03-2025,18,Buscando Money,TWENTY SIX & Tayson Kryss,60,150000,single,2,False,https://i.scdn.co/image/ab67616d0000b27304a5e9...,2025-03-01
14368,01-03-2025,19,A 300,JC Reyes & Pedro Calderon & Blacknife,79,169208,single,1,False,https://i.scdn.co/image/ab67616d0000b273827446...,2025-03-01
14369,01-03-2025,20,CONTIGO (with Tiësto),KAROL G & Tiësto,90,192786,single,1,False,https://i.scdn.co/image/ab67616d0000b273c5426d...,2025-03-01
14370,01-03-2025,21,Columbia,Quevedo,92,186000,single,1,False,https://i.scdn.co/image/ab67616d0000b273a00a81...,2025-03-01
14371,01-03-2025,22,BAD BOY,Chris Jedi & Gaby Music & Dei V,77,235146,single,1,True,https://i.scdn.co/image/ab67616d0000b2734e3fa2...,2025-03-01
14372,01-03-2025,23,MODELITO,Mora,83,190496,album,14,True,https://i.scdn.co/image/ab67616d0000b273076ef0...,2025-03-01
14373,01-03-2025,24,LA CAPI,Myke Towers,80,202360,album,23,True,https://i.scdn.co/image/ab67616d0000b273c75c05...,2025-03-01
14374,01-03-2025,25,REINA,Mora,84,211879,album,15,True,https://i.scdn.co/image/ab67616d0000b2734cc96e...,2025-03-01
14375,01-03-2025,26,DILUVIO,Rauw Alejandro,90,197052,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...,2025-03-01
14376,01-03-2025,27,COSAS QUE NO TE DIJE,Saiko,84,224725,single,1,False,https://i.scdn.co/image/ab67616d0000b273fb045f...,2025-03-01
14377,01-03-2025,28,QLONA,KAROL G,93,172797,album,9,True,https://i.scdn.co/image/ab67616d0000b273d026bf...,2025-03-01
14378,01-03-2025,29,EMPELOTICA,Lenny Tavárez & Feid,77,190322,single,1,True,https://i.scdn.co/image/ab67616d0000b2732733f7...,2025-03-01
14379,01-03-2025,30,Hey Lil Mama,Eladio Carrion,86,216338,album,17,False,https://i.scdn.co/image/ab67616d0000b273ec105e...,2025-03-01
14380,01-03-2025,31,Narcotics (with Bryant Myers),Dei V & Bryant Myers,84,173991,single,1,True,https://i.scdn.co/image/ab67616d0000b2735b8ec2...,2025-03-01
14381,01-03-2025,32,Madrid City,Ana Mena,79,172727,single,1,False,https://i.scdn.co/image/ab67616d0000b2739c3dc8...,2025-03-01
14382,01-03-2025,33,BABY HELLO,Rauw Alejandro,78,222461,album,14,True,https://i.scdn.co/image/ab67616d0000b273f79b1a...,2025-03-01
14383,01-03-2025,34,OA,Anuel AA & Quevedo & Maluma,86,235200,single,1,True,https://i.scdn.co/image/ab67616d0000b27331e30d...,2025-03-01
14384,01-03-2025,35,POLARIS - Remix,Saiko & Feid & Quevedo,83,288000,single,1,True,https://i.scdn.co/image/ab67616d0000b2738f4a27...,2025-03-01
14385,01-03-2025,36,"Japoni (feat. Camin, Moncho Chavea, Jthyago & ...",Oscar el Ruso & Samuel G & Omar Montes,77,248004,single,1,False,https://i.scdn.co/image/ab67616d0000b273dd62eb...,2025-03-01
14386,01-03-2025,37,La Bachata,Manuel Turizo,87,162637,album,15,False,https://i.scdn.co/image/ab67616d0000b2734dd995...,2025-03-01
14387,01-03-2025,38,LALA,Myke Towers,92,197920,album,23,True,https://i.scdn.co/image/ab67616d0000b2730656d5...,2025-03-01
14388,01-03-2025,39,Si No Estás,iñigo quintero,93,184061,single,1,False,https://i.scdn.co/image/ab67616d0000b2735cb953...,2025-03-01
14389,01-03-2025,40,Buenas,Quevedo & Saiko,80,192954,single,1,False,https://i.scdn.co/image/ab67616d0000b27347dde0...,2025-03-01
14390,01-03-2025,41,Quien Es Dei V?,Dei V,81,162244,single,1,True,https://i.scdn.co/image/ab67616d0000b27348093f...,2025-03-01
14391,01-03-2025,42,ASI ES LA VIDA,Enrique Iglesias & Maria Becerra,84,172095,single,1,False,https://i.scdn.co/image/ab67616d0000b2733d2a29...,2025-03-01
14392,01-03-2025,43,lady madrizZz,céro,75,131020,single,1,False,https://i.scdn.co/image/ab67616d0000b2736eb7f1...,2025-03-01
14393,01-03-2025,44,VAGABUNDO,Sebastian Yatra & Manuel Turizo & Beéle,86,215600,single,1,False,https://i.scdn.co/image/ab67616d0000b2732d6016...,2025-03-01
14394,01-03-2025,45,Holanda,Jhayco,86,231693,single,1,True,https://i.scdn.co/image/ab67616d0000b273cd2ceb...,2025-03-01
14395,01-03-2025,46,El Cielo,Sky Rompiendo & Feid & Myke Towers,85,191320,single,1,True,https://i.scdn.co/image/ab67616d0000b27306eccb...,2025-03-01
14396,01-03-2025,47,NO PIENSO LLAMAR,Soge Culebra,70,198352,album,13,False,https://i.scdn.co/image/ab67616d0000b273890db8...,2025-03-01
14397,01-03-2025,48,El Mambo,Kiko Rivera,76,129845,single,1,False,https://i.scdn.co/image/ab67616d0000b2739550e7...,2025-03-01
14398,01-03-2025,49,Tacos Gucci,Anuel AA,84,207157,single,1,True,https://i.scdn.co/image/ab67616d0000b2734b021a...,2025-03-01
14399,01-03-2025,50,TU$$I (with Dei V),YOVNGCHIMI,76,163200,album,16,True,https://i.scdn.co/image/ab67616d0000b2737f78a2...,2025-03-01

In [27]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df.drop(columns=['date_new'], inplace=True)

In [28]:
df.groupby('date').size().value_counts()

50    555
Name: count, dtype: int64

## Normalizing Song and artist naming

In [29]:
df['song'] = df['song'].str.strip().str.lower()
df['artist'] = df['artist'].str.strip().str.lower()